### ISSUE TITLE
pls add ability to turn off trick saber in the mod settings

### ISSUE THREAD

**Issue by BallinAssCat** [Fernthedev/Quest-Trick-Saber#4]
because some of the sabers don't work and the fact that sometime i want to turn it off it becomes annoying to have to quit beat saber open bmbf and turn the mod off other than that this mod is really good.

**Comment by Fernthedev** [comment]
Supporting this feature will be difficult since there are many factors I have to account for in runtime when disabling or enabling aspects of the mod. I'm still not an expert of the code since lots of it are remnants of Michael Zoller's work so adapting it is difficult.

For now this is the way it will have to be.

**Comment by BallinAssCat** [comment]
ok i do have a suggestion to try getting more people to help code /  play test

**Comment by Fernthedev** [comment]
> ok i do have a suggestion to try getting more people to help code / play test

I'm open to ideas but if it's unrelated to this issue it would be better as it's own issue.

**Comment by Fernthedev** [comment]
Closing for now as the feature is not planned to be implemented.
